---
jobs:
  job:
    name: Install perl module
    runs-on: ubuntu-latest
    steps:
    - name: Download repo
      uses: actions/checkout@v2
    - name: Install modules
      run: |
        ls -laR
        #sudo apt install cpanminus
        #cpanm -S Data::Table::Text
        #sudo apt install libexpat1-dev
        #cpanm -S Data::Edit::Xml
        #cpanm -S GitHub::Crud
name: Test Perl
on: push
